In [4]:
import numpy as np

L = list(range(10))

L = np.array(L)

In [5]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.normal(0, 1, (3,3))

array([[ 1.25441407,  1.41910204, -0.74385608],
       [-2.5174371 , -1.50709602,  1.14907613],
       [-1.19357825,  1.14104245,  1.50944508]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.seed(0)


x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


In [14]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1
print(x1[0])

#assess fifth value

print(x1[4])


#get the last value
print(x1[-1])


#get the second last value
print(x1[-2])


#in a multidimensional array, we need to specify row and column index
print(x2)


#1st row and 2nd column value
print(x2[2,3])

#3rd row and last value from the 3rd column
print(x2[2,-1])


#replace value at 0,0 index
x2[0,0] = 12
print(x2)

4
8
4
8
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
7
7
[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [15]:
x = np.arange(10)
print(x)


#from start to 4th position
print(x[:5])



#from 4th position to end
print(x[4:])



#from 4th to 6th position
print(x[4:7])



#return elements at even place
print(x[ : : 2])



#return elements from first position step by two
print(x[1::2])



#reverse the array
print(x[::-1])


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[4 5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]


In [16]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])